name: Scrape historic data

on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: 2020 Galician coronavirus data
      run: |-
        for i in 2020-{10-{07..31},11-{01..30},12-{01..31}};
        do
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_CifrasTotais.csv" > CifrasTotais.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_ActivosCuradosFallecidos.csv" > ActivosCuradosFallecidos.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_InfectadosPorFecha.csv" > InfectadosPorFecha.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_PorcentajeInfectadosPorGenero.csv" > PorcentajeInfectadosPorGenero.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_Fallecidos.csv" > Fallecidos.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_PorcentajeInfeccionesPorFecha.csv" > PorcentajeInfeccionesPorFecha.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_OcupacionCamasHospital.csv" > OcupacionCamasHospital.csv
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
        done
    - name: 2021 Galician coronavirus data
      run: |-
        for i in 2021-{01-{07..31},02-{01..28},03-{01..04}};
        do
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_CifrasTotais.csv" > CifrasTotais.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_ActivosCuradosFallecidos.csv" > ActivosCuradosFallecidos.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_InfectadosPorFecha.csv" > InfectadosPorFecha.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_PorcentajeInfectadosPorGenero.csv" > PorcentajeInfectadosPorGenero.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_Fallecidos.csv" > Fallecidos.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_PorcentajeInfeccionesPorFecha.csv" > PorcentajeInfeccionesPorFecha.csv
          curl "https://coronavirus.sergas.gal/infodatos/${i}_COVID19_Web_OcupacionCamasHospital.csv" > OcupacionCamasHospital.csv
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
        done
